import type { LevelConfig } from './types';

// Multiplayer levels: 40 columns x 20 rows
// Map key: same as solo, plus:
//   1-5 = player spawn points

export const MP_LEVELS: LevelConfig[] = [
  {
    name: 'THE ENTRANCE',
    subtitle: 'A warm welcome to the dungeon',
    map: [
      '########################################',
      '#1  +          #           #          5#',
      '#       S      #     +     #    S      #',
      '#   +      #####           #####   +   #',
      '#          #     T     T       #       #',
      '####  ######   S       S   ====== ####=#',
      '#        +              T  =......=  + #',
      '#   ##      #####     ##   =......=  ##=',
      '#   ##      #   =     =    D......= ## #',
      '#           # .  ...  . .  =......=    #',
      '#           # . .  . . .+. =......=    #',
      '#   ##      #   ========   ======== ## #',
      '#   ##      #####     #####      ##    #',
      '#3       +                        +    #',
      '####  ######   S       S      ######  ##',
      '#          #                   #       #',
      '#   +      #####           #####   +   #',
      '#       S      #     +     #    S      #',
      '#2  +          #     >     #          4#',
      '########################################',
    ],
    fogOfWar: false,
    visionRadius: 99,
    monsterSpeed: 600,
    bossType: 'skeleton',
    bossHpBase: 40,
    monsterCountBase: 4,
  },

  {
    name: 'THE TWIN HALLS',
    subtitle: 'Parallel paths lead to danger',
    map: [
      '########################################',
      '#1  T  +   ##  S   ####   S ##  +  T  5#',
      '#          ##       ##       ##         #',
      '#   S  ##     ## T      ##     ##  S    #',
      '####   ##  T     ####     T  ##   ######',
      '#         ####   #  #   ####            #',
      '#  T  ##    + ## #  # ##  +   ##  T     #',
      '#     ##   S     #  #     S   ##        #',
      '#   ##     ####==#  #==####     ##      #',
      '#  T  ##   =......  ......=   ##  T     #',
      '#     ##   =......  ......=   ##        #',
      '#   ##     ####==#  #==####     ##      #',
      '#     ##   S     #  #     S   ##        #',
      '#  T  ##    + ## #  # ##  +   ##  T     #',
      '#         ####   #  #   ####            #',
      '####   ##  T     ####     T  ##   ######',
      '#   S  ##     ## D    ##     ##  S      #',
      '#          ##       ##       ##         #',
      '#   T  +   ##  +   > ##  +   ##  +  T   #',
      '#3         ##       ####      ##       2#',
      '########################################',
    ],
    fogOfWar: false,
    visionRadius: 99,
    monsterSpeed: 500,
    bossType: 'skeleton',
    bossHpBase: 16,
    monsterCountBase: 6,
  },

  {
    name: 'THE DARK DEPTHS',
    subtitle: 'The darkness conceals ancient terrors',
    map: [
      '########################################',
      '#1  T  +   ##     ####     ##  +  T   5#',
      '#          ##  S     ##  B     ##       #',
      '#   S  ##     ##         ##     ##  S   #',
      '####   ##  T     ####     T  ##   ######',
      '#         ####   #  #   ####            #',
      '#  T  ##      ## #  # ##      ##  T     #',
      '#     ##   B     #  #     S   ##        #',
      '#   ##     ####==#  #==####     ##      #',
      '#2 T  ##   = . . .  . . . =   ## T    3#',
      '#     ##   = . .  .. . .+.=   ##        #',
      '#   ##     ####==#  #==####     ##      #',
      '#     ##   S     #  #     B   ##        #',
      '#  T  ##      ## #  # ##      ##  T     #',
      '#         ####   #  #   ####            #',
      '####   ##  T     ####     T  ##   ######',
      '#   S  ##     ##    D    ##     ##  S   #',
      '#          ##  B     ##       ##        #',
      '#   T  +   ##     ## > ##   +  T        #',
      '#4         ##     ####     ##          >#',
      '########################################',
    ],
    fogOfWar: true,
    visionRadius: 5,
    monsterSpeed: 400,
    bossType: 'slime',
    bossHpBase: 20,
    monsterCountBase: 8,
  },

  {
    name: 'THE INFERNO',
    subtitle: 'Bats swarm from the shadows',
    map: [
      '########################################',
      '#1 T +  #B S# + #^ # T +# S B#  + T 5#',
      '#   ##       #   #      #       ##     #',
      '#  S  ## # #     ## # #     # # ##  S  #',
      '## # #   # ^#  T    ^  T  #^ #   # # ##',
      '#  #T  # #   # + #    # + #   # #  T#  #',
      '# # #####   +    # ## #    +   ##### # #',
      '# +  #S      #   ======   #      S#  + #',
      '# ####     ^     =....=     ^     #### #',
      '#B  #        +   =....=   +        #  B#',
      '## #       +     =....=     +       # ##',
      '#  #  T# + S     =.D..=     S + #T  #  #',
      '#+ #     B  #    ======    #  B     #  +#',
      '# S     +        # ## #        +     S #',
      '#  #  T#  S   #      #   #   S  #T  #  #',
      '## # #   #  ^ # +## ##+ # ^  #   # # ##',
      '#   S  ##     ## T    T ##     ##  S    #',
      '#          ##  B     B    ##            #',
      '#2 T  +    ##    +  >  +  ##    + T    4#',
      '#3         ##     ####     ##          >#',
      '########################################',
    ],
    fogOfWar: true,
    visionRadius: 4,
    monsterSpeed: 300,
    bossType: 'bat',
    bossHpBase: 16,
    monsterCountBase: 12,
  },

  {
    name: 'THE DARK THRONE',
    subtitle: 'Face the Dark Knight or perish together',
    map: [
      '########################################',
      '#1 T + # ^S#B + #^ # T +# S B#  + T 5#',
      '#   ##       # + #      # +     ##     #',
      '#  S  ## # #     ## # #     # # ##  S  #',
      '## ####    # ^#     ^     #^ #    #### #',
      '#T +  B  # #   # + #    # + #   # #  T #',
      '# ### ###   +    # ## #    +   ### ### #',
      '#  S  ^ + ## #   ======   # ##  + ^  S #',
      '# ### ###        =....=        ### ### #',
      '#B  +     # B +  =....=  + B #     +  B#',
      '## ###        +  =....=  +        ### ##',
      '#  S   ##   ^    =.D..=    ^   ##   S  #',
      '# ##       S     ======     S       ## #',
      '#  T    S    B    # ## #    B    S    T #',
      '#  ##  T#       #      #       #T  ##  #',
      '## # #   #   S # +##^##+ # S   #   # ##',
      '#   S  ##     ## T    T ##     ##  S    #',
      '#          ##  B     B    ##            #',
      '#2 T  +    ##    +  >  +  ##    + T    4#',
      '#3         ##     ####     ##          >#',
      '########################################',
    ],
    fogOfWar: true,
    visionRadius: 3,
    monsterSpeed: 220,
    bossType: 'darkKnight',
    bossHpBase: 40,
    monsterCountBase: 15,
  },
];

export function getMPLevelConfig(level: number): LevelConfig {
  if (level < 0 || level >= MP_LEVELS.length) {
    throw new Error(`Invalid MP level ${level}`);
  }
  return MP_LEVELS[level];
}
